name: Build
on: push
jobs:
  build:
    name: Build Tweak
    runs-on: macOS-latest
    env:
      THEOS: theos
    steps:
        - name: Force HTTPS for git
          run: git config --global url."https://github.com/".insteadOf "git://github.com/"
        - name: Checkout
          uses: actions/checkout@master
        - name: Install Dependencies
          run: brew install ldid xz
        - name: Setup Theos
          run: |
            git clone https://github.com/theos/theos.git theos
            cd theos && git checkout 8771215f765e774bfefdacc6ddf0e151c2973d49
            git submodule update --init --recursive
        - name: Download SDKs
          run: |
            curl -LO https://github.com/SamHep0803/iOS-13-Patched-SDK/archive/master.zip
            TMP=$(mktemp -d)
            unzip master.zip -d $TMP
            mv $TMP/iOS-13-Patched-SDK-master/*.sdk theos/sdks
            rm -r master.zip $TMP
        - name: Build Package
          id: build_package
          run: |
            make package FINALPACKAGE=1 ADDITIONAL_CFLAGS="-Wno-error"
            echo "::set-output name=package::$(ls -t packages | head -n1)"
        - name: Upload artifact
          uses: actions/upload-artifact@v4
          with:
            name: carplayenable-deb
            path: packages/*.deb
